BEGIN;

ALTER TABLE go_match
  ADD COLUMN IF NOT EXISTS judge_state JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS judge_history JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS judge_version BIGINT NOT NULL DEFAULT 0;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE go_match TO lpbvolley;

COMMIT;
