'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { CoachIssueOption } from '@/lib/coach/exercise-types';
import type { CoachSkill } from '@/lib/coach/types';
import type { CoachVideoAssetDetail } from '@/lib/coach/video-types';

const field='mt-1 min-h-12 w-full rounded-xl border border-white/12 bg-[#0b111b] px-3 text-sm text-white outline-none focus:border-orange-400';
const formatTime=(ms:number)=>{const seconds=Math.floor(ms/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;};

export default function VideoWorkspace({asset,skills,issues}:{asset:CoachVideoAssetDetail;skills:CoachSkill[];issues:CoachIssueOption[]}){
  const router=useRouter();const[pending,setPending]=useState('');const[error,setError]=useState('');const leafSkills=skills.filter((item)=>item.parentId);
  async function send(event:FormEvent<HTMLFormElement>,kind:'clips'|'frames'|'annotations'){event.preventDefault();const formElement=event.currentTarget;setPending(kind);setError('');const payload=Object.fromEntries(new FormData(formElement).entries()) as Record<string,unknown>;if(payload.startSeconds!=null){payload.startMs=Number(payload.startSeconds)*1000;delete payload.startSeconds;}if(payload.endSeconds!=null){payload.endMs=Number(payload.endSeconds)*1000;delete payload.endSeconds;}if(payload.timestampSeconds!=null){payload.timestampMs=Number(payload.timestampSeconds)*1000;delete payload.timestampSeconds;}const response=await fetch(`/api/coach/media/${asset.id}/${kind}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({})) as {error?:string};setPending('');if(!response.ok){setError(result.error||'Не удалось сохранить разметку');return;}formElement.reset();router.refresh();}
  const sourceUrl=asset.storageUrl||asset.originalUrl;
  const clipOptions=<><option value="">Всё видео</option>{asset.clips.map((clip)=><option key={clip.id} value={clip.id}>{clip.title} · {formatTime(clip.startMs)}–{formatTime(clip.endMs)}</option>)}</>;
  const skillOptions=<><option value="">Без навыка</option>{leafSkills.map((item)=><option key={item.id} value={item.id}>{item.parentName} · {item.name}</option>)}</>;
  const issueOptions=<><option value="">Без проблемы</option>{issues.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</>;
  return <div className="space-y-6"><section className="rounded-3xl border border-white/10 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,.12),transparent_40%),rgba(255,255,255,.035)] p-4 sm:p-6"><Link href="/coach/media" className="inline-flex min-h-11 items-center text-sm text-slate-500 hover:text-orange-300">← Вся медиатека</Link><div className="mt-3 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex flex-wrap gap-2"><span className="rounded-lg bg-cyan-500/10 px-2.5 py-1 text-xs font-black text-cyan-300">{asset.source}</span>{asset.athleteName?<Link href={`/coach/athletes/${asset.athleteId}`} className="rounded-lg bg-white/5 px-2.5 py-1 text-xs text-slate-300">{asset.athleteName}</Link>:null}{asset.exerciseTitle?<Link href={`/coach/exercises/${asset.exerciseId}`} className="rounded-lg bg-white/5 px-2.5 py-1 text-xs text-slate-300">{asset.exerciseTitle}</Link>:null}</div><h1 className="mt-3 font-heading text-4xl text-white sm:text-5xl">{asset.title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">{asset.notes||'Разделите запись на игровые эпизоды и добавьте короткие ручные отметки.'}</p></div><a href={sourceUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-orange-500 px-6 text-sm font-black text-white">▶ Открыть видео</a></div><div className="mt-6 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-black/20 p-3 text-center"><b className="font-heading text-2xl text-white">{asset.clips.length}</b><small className="block text-[9px] uppercase text-slate-600">клипов</small></div><div className="rounded-2xl bg-black/20 p-3 text-center"><b className="font-heading text-2xl text-white">{asset.frames.length}</b><small className="block text-[9px] uppercase text-slate-600">кадров</small></div><div className="rounded-2xl bg-black/20 p-3 text-center"><b className="font-heading text-2xl text-white">{asset.annotations.length}</b><small className="block text-[9px] uppercase text-slate-600">меток</small></div></div></section>
  <section className="rounded-3xl border border-orange-400/20 bg-orange-500/[.035] p-4 sm:p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Шаг 1</p><h2 className="mt-1 font-heading text-3xl text-white">Вырезать эпизод</h2><form onSubmit={(event)=>send(event,'clips')} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="text-xs font-bold text-slate-400">Название<input required minLength={2} name="title" placeholder="Приём короткой подачи" className={field}/></label><label className="text-xs font-bold text-slate-400">Начало, сек<input required name="startSeconds" type="number" min="0" step="0.1" className={field}/></label><label className="text-xs font-bold text-slate-400">Конец, сек<input required name="endSeconds" type="number" min="0.1" step="0.1" className={field}/></label><label className="text-xs font-bold text-slate-400">Навык<select name="skillId" defaultValue="" className={field}>{skillOptions}</select></label><label className="text-xs font-bold text-slate-400">Проблема<select name="issueId" defaultValue="" className={field}>{issueOptions}</select></label><label className="text-xs font-bold text-slate-400 md:col-span-2 xl:col-span-4">Заметка<input name="notes" placeholder="Контекст эпизода" className={field}/></label><button disabled={pending==='clips'} className="min-h-12 self-end rounded-xl bg-orange-500 px-5 text-sm font-black text-white disabled:opacity-50">{pending==='clips'?'…':'Добавить клип'}</button></form></section>
  <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/[.035] p-4 sm:p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Шаг 2</p><h2 className="mt-1 font-heading text-3xl text-white">Ключевой кадр</h2><form onSubmit={(event)=>send(event,'frames')} className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold text-slate-400">Время, сек<input required name="timestampSeconds" type="number" min="0" step="0.1" className={field}/></label><label className="text-xs font-bold text-slate-400">Тип<select name="kind" defaultValue="key" className={field}><option value="key">Ключевой</option><option value="before">До</option><option value="after">После</option><option value="error">Ошибка</option><option value="phase">Фаза</option></select></label><label className="text-xs font-bold text-slate-400 md:col-span-2">Клип<select name="clipId" defaultValue="" className={field}>{clipOptions}</select></label><label className="text-xs font-bold text-slate-400 md:col-span-2">Ссылка на кадр<input required name="imageUrl" placeholder="https://… или /uploads/…" className={field}/></label><label className="text-xs font-bold text-slate-400 md:col-span-2">Подпись<input name="label" placeholder="Контакт справа от корпуса" className={field}/></label><button disabled={pending==='frames'} className="min-h-12 rounded-xl bg-cyan-500/15 px-5 text-sm font-black text-cyan-200 disabled:opacity-50">{pending==='frames'?'…':'Сохранить кадр'}</button></form></section>
  <section className="rounded-3xl border border-white/10 bg-white/[.035] p-4 sm:p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Шаг 3 · вручную</p><h2 className="mt-1 font-heading text-3xl text-white">Поставить отметку</h2><form onSubmit={(event)=>send(event,'annotations')} className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold text-slate-400">Время, сек<input required name="timestampSeconds" type="number" min="0" step="0.1" className={field}/></label><label className="text-xs font-bold text-slate-400">Тип<select name="type" defaultValue="note" className={field}><option value="technique">Техника</option><option value="error">Ошибка</option><option value="cue">Подсказка</option><option value="decision">Решение</option><option value="measurement">Измерение</option><option value="note">Заметка</option></select></label><label className="text-xs font-bold text-slate-400 md:col-span-2">Клип<select name="clipId" defaultValue="" className={field}>{clipOptions}</select></label><label className="text-xs font-bold text-slate-400">Навык<select name="skillId" defaultValue="" className={field}>{skillOptions}</select></label><label className="text-xs font-bold text-slate-400">Проблема<select name="issueId" defaultValue="" className={field}>{issueOptions}</select></label><label className="text-xs font-bold text-slate-400 md:col-span-2">Комментарий<textarea required minLength={2} name="text" rows={3} placeholder="Что видно и что сказать ученику" className={`${field} py-3`}/></label><button disabled={pending==='annotations'} className="min-h-12 rounded-xl bg-emerald-500/15 px-5 text-sm font-black text-emerald-200 disabled:opacity-50">{pending==='annotations'?'…':'Добавить отметку'}</button></form></section></div>{error?<p role="alert" className="rounded-2xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</p>:null}
  <section className="rounded-3xl border border-white/10 bg-white/[.025] p-4 sm:p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Разметка</p><h2 className="mt-1 font-heading text-3xl text-white">Эпизоды и отметки</h2>{asset.clips.length||asset.annotations.length||asset.frames.length?<div className="mt-5 space-y-3">{asset.clips.map((clip)=><article key={clip.id} className="rounded-2xl border border-white/8 bg-black/15 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-black text-white">{clip.title}</h3><b className="text-sm text-orange-300">{formatTime(clip.startMs)}–{formatTime(clip.endMs)}</b></div><p className="mt-1 text-xs text-slate-500">{[clip.skillName,clip.issueTitle,clip.notes].filter(Boolean).join(' · ')}</p></article>)}{asset.annotations.map((annotation)=><article key={annotation.id} className="flex gap-3 rounded-2xl border border-emerald-400/10 bg-emerald-500/[.025] p-4"><b className="shrink-0 text-sm text-emerald-300">{formatTime(annotation.timestampMs)}</b><div><p className="text-sm text-white">{annotation.text}</p><small className="text-slate-600">{[annotation.type,annotation.skillName,annotation.issueTitle].filter(Boolean).join(' · ')}</small></div></article>)}{asset.frames.map((frame)=><a key={frame.id} href={frame.imageUrl} target="_blank" rel="noreferrer" className="flex min-h-14 items-center gap-3 rounded-2xl border border-cyan-400/10 bg-cyan-500/[.025] p-4"><b className="text-sm text-cyan-300">{formatTime(frame.timestampMs)}</b><span className="text-sm text-white">{frame.label||'Ключевой кадр'}</span><small className="ml-auto uppercase text-slate-600">{frame.kind}</small></a>)}</div>:<p className="mt-5 rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">Разметка пока пустая. Начните с одного клипа — это занимает два поля и несколько секунд.</p>}</section></div>;
}
